# Generated by Django 2.2 on 2020-05-13 00:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amplifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(max_length=200, verbose_name='Responsável')),
                ('email', models.EmailField(max_length=254)),
                ('reference', models.CharField(max_length=200, verbose_name='Referência')),
                ('mask', models.FileField(blank=True, null=True, upload_to='csv files/', verbose_name='Máscara (.csv)')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_signal', models.FileField(blank=True, null=True, upload_to='tmp/')),
                ('file_h5', models.FileField(blank=True, null=True, upload_to='tmp/')),
                ('file_info', models.FileField(blank=True, null=True, upload_to='tmp/')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(blank=True, max_length=255, verbose_name='Tipo do Modelo')),
                ('file_h5', models.FileField(blank=True, null=True, upload_to='h5files/', verbose_name='Modelo NN (.h5)')),
                ('file_txt', models.FileField(blank=True, null=True, upload_to='txtfiles/', verbose_name='Informação da rede (.txt)')),
                ('amplifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Amplifier', verbose_name='Amplificador')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_total', models.FloatField()),
                ('pout_total', models.FloatField()),
                ('frequency_ch', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('ganho', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('nf', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('amplifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Amplifier')),
            ],
        ),
        migrations.CreateModel(
            name='RequestPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Título')),
                ('pin_signal', models.FileField(blank=True, null=True, upload_to='requests/', verbose_name='Sinais de entrada (Pin)')),
                ('net_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Modelo', verbose_name='Modelo')),
            ],
        ),
    ]
