# Generated by Django 2.2 on 2020-05-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_requestprediction_ganho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestprediction',
            name='ganho',
        ),
    ]
