# Generated by Django 2.2 on 2020-05-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_requestprediction_ganho'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestprediction',
            name='ganho',
            field=models.IntegerField(default=0),
        ),
    ]
