# Generated by Django 2.2 on 2020-05-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_requestprediction_ganho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestprediction',
            name='ganho',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
