# Generated by Django 2.2 on 2020-05-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200523_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestprediction',
            name='ganho',
            field=models.IntegerField(null=True),
        ),
    ]
