# Generated by Django 2.2.3 on 2020-07-09 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200523_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amplifier',
            name='mask',
            field=models.FileField(blank=True, null=True, upload_to='csv files/', verbose_name='Mask (.csv)'),
        ),
        migrations.AlterField(
            model_name='amplifier',
            name='reference',
            field=models.CharField(max_length=200, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='amplifier',
            name='responsible',
            field=models.CharField(max_length=200, verbose_name='Responsible'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='amplifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Amplifier', verbose_name='Amplifiers'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='file_h5',
            field=models.FileField(blank=True, null=True, upload_to='h5files/', verbose_name='Model NN (.h5)'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='file_txt',
            field=models.FileField(blank=True, null=True, upload_to='txtfiles/', verbose_name='Network information(.txt)'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='model_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Model Type'),
        ),
        migrations.AlterField(
            model_name='requestprediction',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='requestprediction',
            name='net_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Modelo', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='requestprediction',
            name='pin_signal',
            field=models.FileField(blank=True, null=True, upload_to='requests/', verbose_name='Input signal (Pin)'),
        ),
    ]
