# Generated by Django 2.2 on 2020-07-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200709_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amplifier',
            name='mask',
            field=models.FileField(blank=True, null=True, upload_to='csv files/', verbose_name='Mask'),
        ),
    ]
