# Generated by Django 2.2 on 2020-07-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200710_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestprediction',
            name='name',
        ),
    ]
