# Generated by Django 2.2 on 2020-07-26 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_requestprediction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestprediction',
            name='net_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Modelo', verbose_name='Model'),
        ),
    ]
