# Generated by Django 2.2 on 2020-07-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200725_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestprediction',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
    ]
