# Generated by Django 2.2 on 2020-07-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_requestprediction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestprediction',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
    ]
