# Generated by Django 2.2 on 2020-07-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200726_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestprediction',
            name='name',
        ),
    ]
