# Generated by Django 2.2.7 on 2020-08-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_requestprediction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='file_h5',
            field=models.FileField(blank=True, null=True, upload_to='h5files/', verbose_name='Regression Model (.h5)'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='file_txt',
            field=models.FileField(blank=True, null=True, upload_to='txtfiles/', verbose_name='Model Information (.txt)'),
        ),
    ]
